// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/kogleron/youtb/internal/apps"
	"github.com/kogleron/youtb/internal/bootstrap"
)

// Injectors from wire.go:

func initTgbot() (*apps.Tgbot, error) {
	tgbotConf := bootstrap.NewTgbotConf()
	tgbot := apps.NewTgbot(tgbotConf)
	return tgbot, nil
}
